# BADS 7201 Programming for Machine Learning
## Numpy

In [1]:
import numpy as np

## Numpy Arrays

In [2]:
numbers = [1, 2, 3, 4, 5]
numbers

[1, 2, 3, 4, 5]

In [3]:
np.array(numbers)

array([1, 2, 3, 4, 5])

In [4]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
np.random.rand(3)

array([0.00299745, 0.70778434, 0.19344966])

In [15]:
np.random.randn(3)

array([-1.10487395, -1.35738267,  0.19007615])

In [16]:
np.random.randint(1, 100)

53

In [17]:
np.random.randint(1, 100, 10)

array([30,  2, 26, 68, 34, 13, 73, 13, 58, 49])

In [18]:
arr = np.arange(25)

In [19]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
nums = np.random.randint(0, 100, 20)
nums

array([92, 52, 78, 95, 27, 79, 69, 72, 59, 51, 48, 59, 77, 11, 23, 91, 57,
       97, 46, 29])

In [21]:
nums.max()

97

In [22]:
nums.argmax()

17

In [23]:
nums.min()

11

In [24]:
nums.argmin()

13

In [25]:
nums.shape

(20,)

In [26]:
nums.reshape(1, 20).shape

(1, 20)

In [27]:
nums.reshape(20, 1)

array([[92],
       [52],
       [78],
       [95],
       [27],
       [79],
       [69],
       [72],
       [59],
       [51],
       [48],
       [59],
       [77],
       [11],
       [23],
       [91],
       [57],
       [97],
       [46],
       [29]])

In [28]:
nums.reshape(20, 1).shape

(20, 1)

In [29]:
nums.dtype

dtype('int64')

## Numpy Indexing and Selection

In [30]:
nums = np.arange(0, 11)
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
nums[5]

5

In [32]:
nums[1:5]

array([1, 2, 3, 4])

## Broadcasting

In [33]:
nums[0:5] = 10
nums

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [34]:
nums = np.arange(0, 11)
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
nums_slice = nums[0:5]
nums_slice

array([0, 1, 2, 3, 4])

In [36]:
nums_slice[:] = 10
nums_slice

array([10, 10, 10, 10, 10])

In [37]:
nums

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [38]:
nums_copy = nums.copy()
nums_copy

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [39]:
nums_copy[:] = 1
nums_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
nums

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array

In [41]:
matrix = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# Indexing row
matrix[1]

array([4, 5, 6])

In [43]:
matrix[1][0]

4

In [44]:
matrix[1, 0]

4

In [45]:
# 2D array slicing

matrix[:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
matrix[-1]

array([7, 8, 9])

In [47]:
matrix[2, :]

array([7, 8, 9])

In [48]:
matrix = np.zeros((10, 10))
for i in range(matrix.shape[1]):
    matrix[i] = i
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [49]:
matrix[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [50]:
matrix[[9, 4, 5]]

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

### Selection

In [51]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [53]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

## Numpy Operations

In [54]:
arr = np.arange(0, 10)

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [57]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
arr / arr

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [60]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [61]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [62]:
np.max(arr)

9

In [63]:
np.log(arr)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])